# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publytics', '0002_auto_20160703_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouncer',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouncer', to='publytics.Bar'),
        ),
        migrations.AlterField(
            model_name='bouncer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouncer', to=settings.AUTH_USER_MODEL),
        ),
    ]
