# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publytics', '0005_auto_20160809_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='bar',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='publytics.Bar'),
            preserve_default=False,
        ),
    ]
